### ISSUE TITLE
Unhandled exception occurred in onPacketSending(PacketEvent) for MessageEditor

### ISSUE THREAD

**Issue by AfkF24** [jaqobb/message-editor#30]
Not sure whether this is a ProtocolLib issue or simply the fact that Message Editor requires an update to run on MC 1.19.3.

Paper 1.19.3, build 319
ProtocolLib, build 606

```
[14:47:54] [Server thread/ERROR]: [MessageEditor] Unhandled exception occurred in onPacketSending(PacketEvent) for MessageEditor
java.lang.IllegalArgumentException: Unrecognized type class net.minecraft.network.syncher.DataWatcher$b
	at com.comphenix.protocol.wrappers.BukkitConverters$8.getSpecific(BukkitConverters.java:639) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$8.getSpecific(BukkitConverters.java:626) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:43) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters.getSpecificList(BukkitConverters.java:321) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters.access$000(BukkitConverters.java:91) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$3.getSpecific(BukkitConverters.java:365) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$3.getSpecific(BukkitConverters.java:362) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:43) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:274) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:224) ~[ProtocolLib-b606.jar:?]
	at dev.jaqobb.message_editor.message.MessagePlace$12.getMessage(MessagePlace.java:223) ~[MessageEditor-2.4.12.jar:?]
	at dev.jaqobb.message_editor.listener.packet.CommonPacketListener.onPacketSending(CommonPacketListener.java:69) ~[MessageEditor-2.4.12.jar:?]
	at dev.jaqobb.message_editor.listener.packet.EntityNamePacketListener.onPacketSending(EntityNamePacketListener.java:30) ~[MessageEditor-2.4.12.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib-b606.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib-b606.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:430) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2251) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2237) ~[?:?]
	at net.minecraft.server.level.ServerEntity.broadcastAndSend(ServerEntity.java:393) ~[?:?]
	at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java:370) ~[?:?]
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:203) ~[?:?]
	at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:1267) ~[paper-1.19.3.jar:git-Paper-319]
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:1278) ~[paper-1.19.3.jar:git-Paper-319]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:818) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:649) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:709) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1562) ~[paper-1.19.3.jar:git-Paper-319]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[paper-1.19.3.jar:git-Paper-319]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1422) ~[paper-1.19.3.jar:git-Paper-319]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.3.jar:git-Paper-319]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.3.jar:git-Paper-319]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:47:54] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata@778a838e[
    b=2
    c=[b[id=0, serializer=net.minecraft.network.syncher.DataWatcherSerializer$1@5c07294e, value=32], b[id=9, serializer=net.minecraft.network.syncher.DataWatcherSerializer$1@75c91c04, value=20.0], b[id=11, serializer=net.minecraft.network.syncher.DataWatcherSerializer$1@182df4f4, value=true], b[id=17, serializer=net.minecraft.network.syncher.DataWatcherSerializer$1@5c07294e, value=127]]
  ]
```

**Comment by jaqobb** [comment]
Sorry for late reply.

Regarding your issue, ProtocolLib still does not seem to fully support 1.19.3 and the exact same error you provided have already been reported on the ProtocolLib's GitHub page.

For the time being, I recommend staying on 1.19.2, however if you need to stay on 1.19.3 but do not use `ENTITY_NAME` message place, you can also disable `packet-listeners.entity-name` in the configuration file to suppress the error.
