### ISSUE TITLE
ERROR IN CONSOLE

### ISSUE THREAD

**Issue by tomimza** [jaqobb/message-editor#31]
Hi, i have the error, server version: 1.19.2 ProtocoLib Dev Build (support 1.19)

[12:05:52 ERROR]: [MessageEditor] Unhandled exception number 4096 occurred in onPacketSending(PacketEvent) for MessageEditor
java.lang.IllegalArgumentException: handle (WrappedChatComponent[json={"extra":[{"bold":true,"color":"aqua","italic":false,"obfuscated":false,"strikethrough":false,"text":"RECOMPENSAS","underlined":false}],"text":""}]) is not a interface net.minecraft.network.chat.IChatBaseComponent, but class com.comphenix.protocol.wrappers.WrappedChatComponent
        at com.comphenix.protocol.wrappers.AbstractWrapper.setHandle(AbstractWrapper.java:31) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.WrappedChatComponent.<init>(WrappedChatComponent.java:75) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.WrappedChatComponent.fromHandle(WrappedChatComponent.java:85) ~[ProtocolLib.jar:?]
        at dev.jaqobb.message_editor.message.MessagePlace$12.getMessage(MessagePlace.java:258) ~[message-editor-2.5.0-all.jar:?]
        at dev.jaqobb.message_editor.listener.packet.CommonPacketListener.onPacketSending(CommonPacketListener.java:69) ~[message-editor-2.5.0-all.jar:?]
        at dev.jaqobb.message_editor.listener.packet.EntityNamePacketListener.onPacketSending(EntityNamePacketListener.java:30) ~[message-editor-2.5.0-all.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:431) ~[?:?]
        at net.minecraft.network.Connection.processQueue(Connection.java:541) ~[?:?]
        at net.minecraft.network.Connection.flushQueue(Connection.java:504) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:559) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1577) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1409) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:308) ~[paper-1.19.2.jar:git-light-"aaf5e39"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by jaqobb** [comment]
Hello, for the time being I recommend setting `packet-listeners.entity-name` to `false` to hide the error, but only if you do not edit entity names at all in the first place.

After that please wait for the update that should be released soon.
