### ISSUE TITLE
Plugin wont load

### ISSUE THREAD

**Issue by justbrekii** [jaqobb/message-editor#34]
Hey!
I've pasted the plugin into my plugins folder on a PaperMC 1.16.5 server and it won't work. It won't even show op in the plugins list for some reason. Could you help me please?

**Comment by justbrekii** [comment]
Ok I've forgot to download protocollib but even after downloading it still shows up as red in the plugin list.
I get this error message:
"[17:32:43 INFO]: [MessageEditor] Enabling MessageEditor v2.5.1
[17:32:43 INFO]: [MessageEditor] Starting updater...
[17:32:43 INFO]: [MessageEditor] Starting menu manager...
[17:32:44 ERROR]: Error occurred while enabling MessageEditor v2.5.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.accessors.FieldAccessor com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessorOrNull(java.lang.Class, java.lang.String, java.lang.Class)'
        at dev.jaqobb.message_editor.menu.MenuManager.constructArrowItem(MenuManager.java:239) ~[?:?]
        at dev.jaqobb.message_editor.menu.MenuManager.<clinit>(MenuManager.java:85) ~[?:?]
        at dev.jaqobb.message_editor.MessageEditorPlugin.onEnable(MessageEditorPlugin.java:139) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]"

**Comment by justbrekii** [comment]
And I get this too:
[17:47:01 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] SYSTEM_CHAT initializing MessageEditor v2.5.1 (Is it up to date?)
java.lang.NoSuchFieldError: SYSTEM_CHAT
        at dev.jaqobb.message_editor.message.MessagePlace.<clinit>(MessagePlace.java:58) ~[?:?]
        at dev.jaqobb.message_editor.MessageEditorPlugin.onLoad(MessageEditorPlugin.java:102) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by jaqobb** [comment]
Hello,

The first error can be fixed by updating your ProtocolLib version to the latest dev build. You can download it here: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

The second error might be related to the first one, so verify if it still persists after updating ProtocolLib and if so, paste up-to-date error message here.

**Comment by justbrekii** [comment]
Thank you so much for your help! It works. Have a nice day man!
