### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kosmetrol** [jaqobb/message-editor#38]
[19:12:45] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:12:46] [ServerMain/INFO]: Loaded 7 recipes
[19:12:47] [Server thread/INFO]: Starting minecraft server version 1.19.4
[19:12:47] [Server thread/WARN]: ****************************
[19:12:47] [Server thread/WARN]: YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
[19:12:47] [Server thread/WARN]: YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
[19:12:47] [Server thread/WARN]: FOR MORE INFORMATION, SEE https://madelinemiller.dev/blog/root-minecraft-server/
[19:12:47] [Server thread/WARN]: ****************************
[19:12:47] [Server thread/INFO]: Loading properties
[19:12:47] [Server thread/INFO]: This server is running Purpur version git-Purpur-1957 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: f952106 on HEAD)
[19:12:47] [Server thread/INFO]: Server Ping Player Sample Count: 12
[19:12:47] [Server thread/INFO]: Using 4 threads for Netty based IO
[19:12:47] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[19:12:47] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[19:12:48] [Server thread/WARN]: [Pufferfish] Will not enable SIMD! These optimizations are only safely supported on Java 17, Java 18, and Java 19.
[19:12:48] [Server thread/INFO]: Default game type: SURVIVAL
[19:12:48] [Server thread/INFO]: Generating keypair
[19:12:48] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:50006
[19:12:48] [Server thread/INFO]: Using default channel type
[19:12:48] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[19:12:48] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[19:12:49] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.0.0-SNAPSHOT-634
[19:12:50] [Server thread/INFO]: [spark] Loading server plugin spark v1.10.37
[19:12:50] [Server thread/INFO]: [MessageEditor] Loading server plugin MessageEditor v2.5.1
[19:12:50] [Server thread/ERROR]: [MessageEditor] Error initializing plugin 'message-editor-2.5.1-all.jar' in folder 'plugins' (Is it up to date?)
java.lang.IllegalAccessError: class dev.jaqobb.message_editor.message.MessagePlace tried to access private method 'boolean com.comphenix.protocol.utility.MinecraftVersion.atOrAbove(com.comphenix.protocol.utility.MinecraftVersion)' (dev.jaqobb.message_editor.message.MessagePlace is in unnamed module of loader 'message-editor-2.5.1-all.jar' @2ffb7f27; com.comphenix.protocol.utility.MinecraftVersion is in unnamed module of loader 'ProtocolLib.jar' @16bc0a23)
	at dev.jaqobb.message_editor.message.MessagePlace.<init>(MessagePlace.java:347) ~[message-editor-2.5.1-all.jar:?]
	at dev.jaqobb.message_editor.message.MessagePlace.<init>(MessagePlace.java:45) ~[message-editor-2.5.1-all.jar:?]
	at dev.jaqobb.message_editor.message.MessagePlace$1.<init>(MessagePlace.java:47) ~[message-editor-2.5.1-all.jar:?]
	at dev.jaqobb.message_editor.message.MessagePlace.<clinit>(MessagePlace.java:47) ~[message-editor-2.5.1-all.jar:?]
	at dev.jaqobb.message_editor.MessageEditorPlugin.onLoad(MessageEditorPlugin.java:102) ~[message-editor-2.5.1-all.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:36) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:437) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[19:12:50] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:12:50] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.0.0-SNAPSHOT-634
[19:12:50] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[19:12:50] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[19:12:50] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[19:12:50] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[19:12:50] [Server thread/INFO]: Preparing level "world"
[19:12:50] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[19:12:50] [Server thread/INFO]: Time elapsed: 100 ms
[19:12:50] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[19:12:50] [Server thread/INFO]: Time elapsed: 26 ms
[19:12:50] [Server thread/INFO]: [spark] Enabling spark v1.10.37
[19:12:51] [Server thread/INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[19:12:51] [Server thread/INFO]: [spark] Starting background profiler...
[19:12:51] [Server thread/INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows10/amd64), so the built-in Java engine will be used instead.
[19:12:51] [Server thread/INFO]: [MessageEditor] Enabling MessageEditor v2.5.1
[19:12:51] [Server thread/INFO]: [MessageEditor] Starting updater...
[19:12:51] [Server thread/INFO]: [MessageEditor] Starting menu manager...
[19:12:51] [Server thread/INFO]: [MessageEditor] Registering command...
[19:12:51] [Server thread/INFO]: [MessageEditor] Registering listeners...
[19:12:51] [Server thread/INFO]: [MessageEditor] Registering packet listeners...
[19:12:51] [Server thread/WARN]: [MessageEditor] Could not create 'edits' directory.
[19:12:51] [Server thread/ERROR]: Error occurred while enabling MessageEditor v2.5.1 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class dev.jaqobb.message_editor.message.MessagePlace
	at dev.jaqobb.message_editor.listener.packet.KickPacketListener.<init>(KickPacketListener.java:33) ~[message-editor-2.5.1-all.jar:?]
	at dev.jaqobb.message_editor.MessageEditorPlugin.onEnable(MessageEditorPlugin.java:159) ~[message-editor-2.5.1-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:569) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:480) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalAccessError: class dev.jaqobb.message_editor.message.MessagePlace tried to access private method 'boolean com.comphenix.protocol.utility.MinecraftVersion.atOrAbove(com.comphenix.protocol.utility.MinecraftVersion)' (dev.jaqobb.message_editor.message.MessagePlace is in unnamed module of loader 'message-editor-2.5.1-all.jar' @2ffb7f27; com.comphenix.protocol.utility.MinecraftVersion is in unnamed module of loader 'ProtocolLib.jar' @16bc0a23) [in thread "Server thread"]
	at dev.jaqobb.message_editor.message.MessagePlace.<init>(MessagePlace.java:347) ~[message-editor-2.5.1-all.jar:?]
	at dev.jaqobb.message_editor.message.MessagePlace.<init>(MessagePlace.java:45) ~[message-editor-2.5.1-all.jar:?]
	at dev.jaqobb.message_editor.message.MessagePlace$1.<init>(MessagePlace.java:47) ~[message-editor-2.5.1-all.jar:?]
	at dev.jaqobb.message_editor.message.MessagePlace.<clinit>(MessagePlace.java:47) ~[message-editor-2.5.1-all.jar:?]
	at dev.jaqobb.message_editor.MessageEditorPlugin.onLoad(MessageEditorPlugin.java:102) ~[message-editor-2.5.1-all.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:36) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:437) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[purpur-1.19.4.jar:git-Purpur-1957]
	... 3 more
[19:12:51] [Server thread/INFO]: [MessageEditor] Disabling MessageEditor v2.5.1
[19:12:51] [Server thread/INFO]: Starting remote control listener
[19:12:51] [Server thread/INFO]: Thread RCON Listener started
[19:12:51] [Server thread/INFO]: RCON running on 0.0.0.0:50605
[19:12:51] [Server thread/INFO]: Running delayed init tasks
[19:12:51] [Server thread/INFO]: Done (3.945s)! For help, type "help"

**Comment by jaqobb** [comment]
The newest version of ProtocolLib had a change in some parts of the API that Message Editor is using. In order to fix the startup issue, either downgrade ProtocolLib or use the snapshot version of Message Editor that uses the new API.

You can download said Message Editor version here: https://github.com/jaqobb/message-editor/suites/12058217140/artifacts/634241982

**Comment by jaqobb** [comment]
Message Editor 2.5.2 has been released, fixing Paper issue and bumping ProtocolLib API among other things.
